version: '3'
services:
  collector-nvd-nist-cve:
    image: openbas/collector-nvd-nist-cve:latest
    environment:
      - OPENBAS_URL=${OPENBAS_URL}
      - OPENBAS_TOKEN=${OPENBAS_TOKEN}
      - COLLECTOR_ID=${COLLECTOR_ID}
      - COLLECTOR_NAME=${COLLECTOR_NAME:-"Cve by NVD NIST"}
      - COLLECTOR_LOG_LEVEL=${COLLECTOR_LOG_LEVEL:-warn}
      - COLLECTOR_PERIOD=${COLLECTOR_PERIOD:-7200}
      - COLLECTOR_TYPE=${COLLECTOR_TYPE:-nvd_nist_cve}
      - NVD_NIST_CVE_API_BASE_URL=${NVD_NIST_CVE_API_BASE_URL:-https://services.nvd.nist.gov/rest/json}
      - NVD_NIST_CVE_API_KEY=${NVD_NIST_CVE_API_KEY}
    restart: unless-stopped
