services:
  collector-openbas:
    image: openbas/collector-openbas:latest
    environment:
      - OPENBAS_URL=${OPENBAS_URL}
      - OPENBAS_TOKEN=${OPENBAS_TOKEN}
      - COLLECTOR_ID=${COLLECTOR_ID}
      - COLLECTOR_NAME=${COLLECTOR_NAME:-"OpenBAS Datasets"}
      - COLLECTOR_LOG_LEVEL=${COLLECTOR_LOG_LEVEL:-warn}
      - COLLECTOR_PERIOD=${COLLECTOR_PERIOD:-604800}
      - COLLECTOR_TYPE=${COLLECTOR_TYPE:-openbas}
      - OPENBAS_URL_PREFIX=${OPENBAS_URL_PREFIX:-https://raw.githubusercontent.com/OpenBAS-Platform/payloads/refs/heads/main/}
      - OPENBAS_IMPORT_ONLY_NATIVE=${OPENBAS_IMPORT_ONLY_NATIVE:-false}
    restart: unless-stopped
