version: '3'
services:
  collector-microsoft-defender:
    image: openbas/collector-microsoft-defender:1.0.6
    environment:
      - OPENBAS_URL=http://localhost
      - OPENBAS_TOKEN=ChangeMe
      - COLLECTOR_ID=ChangeMe
      - "COLLECTOR_NAME=Microsoft Defender"
      - COLLECTOR_LOG_LEVEL=error
      - MICROSOFT_DEFENDER_TENANT_ID=
      - MICROSOFT_DEFENDER_CLIENT_ID=
      - MICROSOFT_DEFENDER_CLIENT_SECRET=
    restart: always
